[workspace]
members = ["crates/protocol", "crates/worker"]
exclude = ["historical/base"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.96"
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "deny"

[workspace.lints.clippy]
all = "warn"
